import express from 'express';
import nodemailer from 'nodemailer';

const router = express.Router();

// POST /api/sos/email - Send SOS email alert
router.post('/email', async (req, res) => {
  try {
    const { patientName, patientEmail, sosType, medicalInfo, location } = req.body;

    if (!patientName || !sosType) {
      return res.status(400).json({ message: 'Missing required fields' });
    }

    // Create transporter using Gmail SMTP
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    const alertTypeLabel = {
      manual: '🆘 Manual Emergency Call',
      fall: '⚠️ Fall Detected',
      heart_rate: '❤️ Abnormal Heart Rate',
      blood_pressure: '🩺 Blood Pressure Alert',
    }[sosType] || sosType;

    const locationText = location?.address || 'Location unavailable';
    const bloodType = medicalInfo?.bloodType || 'Unknown';
    const allergies = medicalInfo?.allergies?.join(', ') || 'None recorded';
    const conditions = medicalInfo?.medicalConditions?.join(', ') || 'None recorded';
    const medications = medicalInfo?.medications?.join(', ') || 'None recorded';
    const emergencyNotes = medicalInfo?.emergencyNotes || 'None';

    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 2px solid #e53e3e; border-radius: 12px;">
        <div style="background: linear-gradient(135deg, #c53030, #e53e3e); padding: 20px; border-radius: 8px; text-align: center; margin-bottom: 20px;">
          <h1 style="color: white; margin: 0; font-size: 28px;">🚨 EMERGENCY SOS ALERT</h1>
          <p style="color: #fed7d7; margin: 8px 0 0 0;">${alertTypeLabel}</p>
        </div>

        <div style="background: #fff5f5; border-left: 4px solid #e53e3e; padding: 16px; border-radius: 4px; margin-bottom: 20px;">
          <h2 style="color: #c53030; margin: 0 0 8px 0;">Patient: ${patientName}</h2>
          <p style="margin: 4px 0; color: #555;">📍 <strong>Location:</strong> ${locationText}</p>
          <p style="margin: 4px 0; color: #555;">🕐 <strong>Time:</strong> ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</p>
          ${patientEmail ? `<p style="margin: 4px 0; color: #555;">📧 <strong>Patient Email:</strong> ${patientEmail}</p>` : ''}
        </div>

        <div style="background: #f7fafc; padding: 16px; border-radius: 8px; margin-bottom: 20px;">
          <h3 style="color: #2d3748; margin: 0 0 12px 0; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">🏥 Medical Information</h3>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 6px 0; color: #718096; width: 40%;"><strong>Blood Type</strong></td>
              <td style="padding: 6px 0; color: #2d3748;">${bloodType}</td>
            </tr>
            <tr style="background: #edf2f7;">
              <td style="padding: 6px 8px; color: #718096;"><strong>Known Allergies</strong></td>
              <td style="padding: 6px 8px; color: #2d3748;">${allergies}</td>
            </tr>
            <tr>
              <td style="padding: 6px 0; color: #718096;"><strong>Medical Conditions</strong></td>
              <td style="padding: 6px 0; color: #2d3748;">${conditions}</td>
            </tr>
            <tr style="background: #edf2f7;">
              <td style="padding: 6px 8px; color: #718096;"><strong>Current Medications</strong></td>
              <td style="padding: 6px 8px; color: #2d3748;">${medications}</td>
            </tr>
            <tr>
              <td style="padding: 6px 0; color: #718096;"><strong>Emergency Notes</strong></td>
              <td style="padding: 6px 0; color: #2d3748;">${emergencyNotes}</td>
            </tr>
          </table>
        </div>

        <div style="background: #e53e3e; color: white; padding: 14px; border-radius: 8px; text-align: center;">
          <p style="margin: 0; font-weight: bold; font-size: 16px;">⚡ PLEASE RESPOND IMMEDIATELY</p>
          <p style="margin: 8px 0 0 0; font-size: 13px; opacity: 0.9;">This alert was auto-generated by ElderEase. Caregiver portal is live-synced.</p>
        </div>
      </div>
    `;

    await transporter.sendMail({
      from: `"ElderEase SOS 🚨" <${process.env.EMAIL_USER}>`,
      to: 'nehanishad607@gmail.com',
      subject: `🚨 SOS ALERT — ${patientName} needs help! [${alertTypeLabel}]`,
      html: emailHtml,
    });

    res.json({ success: true, message: 'Emergency email sent.' });
  } catch (error) {
    console.error('Email error:', error.message);
    res.status(500).json({ message: 'Failed to send email', error: error.message });
  }
});

export default router;
